Importing Libraries and Defining Data

In [18]:
import numpy as np

# Ground truth labels (one-hot encoded)
y_true = np.array([
    [1, 0, 0],  # Sample 1: Class 1
    [0, 1, 0],  # Sample 2: Class 2
    [0, 0, 1]   # Sample 3: Class 3
])

# Model predictions (logits)
logits = np.array([
    [2.0, 1.0, 0.1],  # Sample 1
    [0.5, 2.5, 0.2],  # Sample 2
    [0.1, 0.2, 3.0]   # Sample 3
])

print("Ground Truth Labels (y_true):")
print(y_true)
print("\nModel Predictions (Logits):")
print(logits)

Ground Truth Labels (y_true):
[[1 0 0]
 [0 1 0]
 [0 0 1]]

Model Predictions (Logits):
[[2.  1.  0.1]
 [0.5 2.5 0.2]
 [0.1 0.2 3. ]]


Defining the Softmax Function

In [19]:
# Softmax function
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))  # Numerical stability
    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)

print("Softmax function has been defined.")

Softmax function has been defined.


Computing Softmax Probabilities

In [20]:
# Compute softmax probabilities
probs = softmax(logits)
print("Softmax Probabilities:")
print(probs)

Softmax Probabilities:
[[0.65900114 0.24243297 0.09856589]
 [0.10953053 0.80932725 0.08114221]
 [0.04931133 0.05449744 0.89619123]]


Computing the Log of Softmax Probabilities

In [21]:
# Compute log(probs)
log_probs = np.log(probs)
print("\nLog of Softmax Probabilities:")
print(log_probs)


Log of Softmax Probabilities:
[[-0.41703002 -1.41703002 -2.31703002]
 [-2.21155193 -0.21155193 -2.51155193]
 [-3.00960146 -2.90960146 -0.10960146]]


Calculating y_true * log(probs)

In [22]:
# Compute y_true * log(probs)
y_true_log_probs = y_true * log_probs
print("\n y_true * log(probs):")
print(y_true_log_probs)


 y_true * log(probs):
[[-0.41703002 -0.         -0.        ]
 [-0.         -0.21155193 -0.        ]
 [-0.         -0.         -0.10960146]]


Computing Cross-Entropy Loss for Each Sample

In [23]:
# Compute CE loss for each sample
ce_loss = -np.sum(y_true_log_probs, axis=-1)
print("\nCE Loss per Sample:")
print(ce_loss)


CE Loss per Sample:
[0.41703002 0.21155193 0.10960146]


Computing Average Cross-Entropy Loss for the Dataset

In [24]:
# Average CE loss for the dataset
avg_ce_loss = np.mean(ce_loss)
print("\nAverage CE Loss for the Dataset:")
print(avg_ce_loss)


Average CE Loss for the Dataset:
0.24606113655369521
